version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  myapp:
    tty: true
    build: ./docker/myapp
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./docker/myapp/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
