#!/bin/bash

REMOTE_HOST=$(/sbin/ip route | awk '/default/ { print $3 }')
export XDEBUG_CONFIG="idekey=eclipse_dbgp remote_host=$REMOTE_HOST"
export APP_ENV="testing"
echo "CONFIG: $XDEBUG_CONFIG"
./vendor/bin/phpunit $@